name: document
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - run: npm ci
      - run: npm run build:doc
      - uses: actions/upload-pages-artifact@v2
        with:
          path: doc
      - uses: actions/deploy-pages@v3
        if: github.ref == 'refs/heads/main'
