name: release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: ${{ github.ref == 'refs/heads/main' && 'release' || '' }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: raviqqe/pnpm-publish@v2
        with:
          release: ${{ github.ref == 'refs/heads/main' }}
  jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - run: npx jsr publish ${{ github.ref == 'refs/heads/main' && '--' || '--dry-run' }}
