name: release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - run: ./.github/actions/setup
      - uses: raviqqe/pnpm-publish@v1
        with:
          npm_token: ${{ github.ref == 'refs/heads/main' && secrets.NPM_TOKEN || '' }}
  jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - run: npx jsr publish ${{ github.ref == 'refs/heads/main' && '--' || '--dry-run' }}
